apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: demo-app
  namespace: flux-system
spec:
  path: ./manifests/demo-app
  prune: true
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
